# Generated by Django 4.0.5 on 2022-07-12 19:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='breakfast',
            field=models.CharField(default='eggs', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='log date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='day_notes',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='day_rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='dinner',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='fatigue_lvl',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='lunch',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='meds',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='mood',
            field=models.CharField(choices=[('5', 'Big Smile'), ('4', 'Slight Smile'), ('3', 'Neutral'), ('2', 'Slight Frown'), ('1', 'Big Frown')], default='5', max_length=1),
        ),
        migrations.AddField(
            model_name='log',
            name='pain_lvl',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='sleep_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='snacks',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='time_outside',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='water_cups',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
