# Generated by Django 4.0.5 on 2022-07-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_log_breakfast_log_date_log_day_notes_log_day_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='mood',
            field=models.CharField(choices=[(':D', 'Big Smile'), (':)', 'Slight Smile'), (':|', 'Neutral'), ('):', 'Slight Frown'), ('D:', 'Big Frown')], default=':D', max_length=2),
        ),
    ]
