# Generated by Django 4.0.5 on 2022-07-13 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_log_mood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='log',
            name='breakfast',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='day_notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='log',
            name='day_rating',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='log',
            name='dinner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='fatigue_lvl',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='log',
            name='lunch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='meds',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='log',
            name='mood',
            field=models.CharField(blank=True, choices=[(':D', 'Big Smile'), (':)', 'Slight Smile'), (':|', 'Neutral'), ('):', 'Slight Frown'), ('D:', 'Big Frown')], default=':D', max_length=2),
        ),
        migrations.AlterField(
            model_name='log',
            name='pain_lvl',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='log',
            name='sleep_hours',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='snacks',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_outside',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='water_cups',
            field=models.IntegerField(blank=True),
        ),
    ]
