# Generated by Django 4.0.5 on 2022-07-13 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_log_options_alter_log_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='breakfast',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='day_notes',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='log',
            name='day_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='log',
            name='dinner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='fatigue_lvl',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='log',
            name='lunch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='meds',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='log',
            name='pain_lvl',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='log',
            name='sleep_hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='snacks',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='time_outside',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='water_cups',
            field=models.IntegerField(),
        ),
    ]
